### ISSUE TITLE
step 6-7: Biopython package installation

### ISSUE THREAD

**Issue by rrohwer** [McMahonLab/16STaxAss#69]
Also need to check for and install PIP for those users who never installed any python package before ever ;)

```
$ python find_seqIDs_blast_removed.py otus.fasta otus.custom.blast.table.modified ids.below.98
BioPython not installed. Trying with pip.
Traceback (most recent call last):
  File "find_seqIDs_blast_removed.py", line 29, in <module>
    import pip
ImportError: No module named pip
```

**Comment by rrohwer** [comment]
@joshamilton OK, so I tried your biopython fix.  

I got this error in the command line (after reeeeaaaaalllly long output of copying/creating/etc):

```
    copying Bio/PopGen/SimCoal/data/split_ssm_2d.par -> build/lib.macosx-10.10-intel-2.7/Bio/PopGen/SimCoal/data
    copying Bio/PopGen/SimCoal/data/ssm_1d.par -> build/lib.macosx-10.10-intel-2.7/Bio/PopGen/SimCoal/data
    copying Bio/PopGen/SimCoal/data/ssm_2d.par -> build/lib.macosx-10.10-intel-2.7/Bio/PopGen/SimCoal/data
    running build_ext
    building 'Bio.cpairwise2' extension
    creating build/temp.macosx-10.10-intel-2.7
    creating build/temp.macosx-10.10-intel-2.7/Bio
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Bio/cpairwise2module.c -o build/temp.macosx-10.10-intel-2.7/Bio/cpairwise2module.o
    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-sQbQcc/biopython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bNJMXf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-sQbQcc/biopython
Traceback (most recent call last):
  File "find_seqIDs_blast_removed.py", line 51, in <module>
    from Bio import SeqIO
ImportError: No module named Bio
```

And this pop-up box:
![image](https://cloud.githubusercontent.com/assets/4306194/12502457/8070b280-c08e-11e5-862b-98b9ec04adc9.png)

I didn't install xcode on my new laptop because it always annoyingly opened very very very slowly on my old one.  maybe I should?

**Comment by rrohwer** [comment]
@joshamilton OK, so I said "Install" and it took like 5 minutes and then I re-ran the command and I got a completion message, but I also got a bunch of error messages:

```
cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. -Qunused-arguments -Qunused-arguments build/temp.macosx-10.10-intel-2.7/Bio/PDB/QCPSuperimposer/qcprotmodule.o -o build/lib.macosx-10.10-intel-2.7/Bio/PDB/QCPSuperimposer/qcprotmodule.so
    running install_lib
    creating /Library/Python/2.7/site-packages/Bio
    error: could not create '/Library/Python/2.7/site-packages/Bio': Permission denied

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mc/k9h2668x21vd_3ppxrkb5z7h0000gn/T/pip-build-xTbMR2/biopython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mc/k9h2668x21vd_3ppxrkb5z7h0000gn/T/pip-MFJcKZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/mc/k9h2668x21vd_3ppxrkb5z7h0000gn/T/pip-build-xTbMR2/biopython
Password:
The directory '/Users/athena/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/athena/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting biopython
  Downloading biopython-1.66.tar.gz (13.7MB)
    100% |████████████████████████████████| 13.7MB 38kB/s
Installing collected packages: biopython
  Running setup.py install for biopython ... done
Successfully installed biopython-1.66
Appending sequences not found by BLAST to ids.below.98
Assign taxonomy to these sequences using the Large General database
```

**Comment by rrohwer** [comment]
But also of note, it did appear to work:

```
$ wc -l ids*
     930 ids.above.98
   16838 ids.below.98
   17768 total
```

those numbers are correct for the number of sequences there should be.  

I think it would be better though to create a completely new ids list and then add that one on, in case you need to re-run the step, so that you don't get things doubly appending and don't have to go back and repeat step 4?  this is what happened when I re-ran the step with everything installed (no errors btw)

```
$ wc -l ids*
     930 ids.above.98
   19435 ids.below.98
   20365 total
```

**Comment by joshamilton** [comment]
@rrohwer I will "revert" the script to read in the fasta files directly and submit a pull request with the simplified scripts. I'll also modify the scripts to append missing IDs to ids.missing.98 and we can re-insert the manual concatenation step.

**Comment by rrohwer** [comment]
Can you show me how you do the reversion?  I don't know how yet.

On Fri, Jan 22, 2016 at 1:16 PM, Joshua J Hamilton <notifications@github.com

**Comment by rrohwer** [comment]
reversion complete.  we have crawled back into the swamp.
